### PR TITLE
Delete new_remote.txt

### PR DESCRIPTION
**Pull request by senthilkgh**

### CODE REVIEW

**Review by senthilkgh — COMMENTED** [review]
reviewed

**Review by tempsen — APPROVED** [review]

**Comment by tempsen** [comment]
dsfadf

**Review by tempsen — APPROVED** [review]
validated and approving the changes made

**Comment by tempsen** [comment]
ffff

**Review by tempsen — APPROVED** [review]
viewed and approved

**Review by tempsen — APPROVED** [review]
reviewed and approving from tempsen userid

**Comment by senthilkgh** [comment]
xddd

**Pull request closed without merging**
